import type { Department, Municipality } from "./place";

export const DEPARTMENTS: readonly Department[] = [
  { code: "01", name: "Guatemala" },
  { code: "02", name: "El Progreso" },
  { code: "03", name: "Sacatepéquez" },
  { code: "04", name: "Chimaltenango" },
  { code: "05", name: "Escuintla" },
  { code: "06", name: "Santa Rosa" },
  { code: "07", name: "Sololá" },
  { code: "08", name: "Totonicapán" },
  { code: "09", name: "Quetzaltenango" },
  { code: "10", name: "Suchitepéquez" },
  { code: "11", name: "Retalhuleu" },
  { code: "12", name: "San Marcos" },
  { code: "13", name: "Huehuetenango" },
  { code: "14", name: "Quiché" },
  { code: "15", name: "Baja Verapaz" },
  { code: "16", name: "Alta Verapaz" },
  { code: "17", name: "Petén" },
  { code: "18", name: "Izabal" },
  { code: "19", name: "Zacapa" },
  { code: "20", name: "Chiquimula" },
  { code: "21", name: "Jalapa" },
  { code: "22", name: "Jutiapa" },
];

export const MUNICIPALITIES: readonly Municipality[] = [
  {
    code: "0101",
    name: "Guatemala",
    departmentCode: "01",
    zones: [
      "Zona 1",
      "Zona 2",
      "Zona 3",
      "Zona 4",
      "Zona 5",
      "Zona 6",
      "Zona 7",
      "Zona 8",
      "Zona 9",
      "Zona 10",
      "Zona 11",
      "Zona 12",
      "Zona 13",
      "Zona 14",
      "Zona 15",
      "Zona 16",
      "Zona 17",
      "Zona 18",
      "Zona 19",
      "Zona 20",
      "Zona 21",
      "Zona 22",
      "Zona 23",
      "Zona 24",
      "Zona 25",
    ],
  },
  { code: "0102", name: "Santa Catarina Pinula", departmentCode: "01", zones: [] },
  { code: "0103", name: "San José Pinula", departmentCode: "01", zones: [] },
  { code: "0104", name: "San José del Golfo", departmentCode: "01", zones: [] },
  { code: "0105", name: "Palencia", departmentCode: "01", zones: [] },
  { code: "0106", name: "Chinautla", departmentCode: "01", zones: [] },
  { code: "0107", name: "San Pedro Ayampuc", departmentCode: "01", zones: [] },
  {
    code: "0108",
    name: "Mixco",
    departmentCode: "01",
    zones: [
      "Zona 1",
      "Zona 2",
      "Zona 3",
      "Zona 4",
      "Zona 5",
      "Zona 6",
      "Zona 7",
      "Zona 8",
      "Zona 9",
      "Zona 10",
      "Zona 11",
    ],
  },
  { code: "0109", name: "San Pedro Sacatepéquez", departmentCode: "01", zones: [] },
  { code: "0110", name: "San Juan Sacatepéquez", departmentCode: "01", zones: [] },
  { code: "0111", name: "San Raymundo", departmentCode: "01", zones: [] },
  { code: "0112", name: "Chuarrancho", departmentCode: "01", zones: [] },
  { code: "0113", name: "Fraijanes", departmentCode: "01", zones: [] },
  { code: "0114", name: "Amatitlán", departmentCode: "01", zones: [] },
  {
    code: "0115",
    name: "Villa Nueva",
    departmentCode: "01",
    zones: [
      "Zona 1",
      "Zona 2",
      "Zona 3",
      "Zona 4",
      "Zona 5",
      "Zona 6",
      "Zona 7",
      "Zona 8",
      "Zona 9",
      "Zona 10",
      "Zona 11",
      "Zona 12",
      "Zona 13",
      "Zona 14",
    ],
  },
  { code: "0116", name: "Villa Canales", departmentCode: "01", zones: [] },
  { code: "0117", name: "San Miguel Petapa", departmentCode: "01", zones: [] },
  { code: "0201", name: "Guastatoya", departmentCode: "02", zones: [] },
  { code: "0202", name: "Morazán", departmentCode: "02", zones: [] },
  { code: "0203", name: "San Agustín Acasaguastlán", departmentCode: "02", zones: [] },
  { code: "0204", name: "San Cristóbal Acasaguastlán", departmentCode: "02", zones: [] },
  { code: "0205", name: "El Jícaro", departmentCode: "02", zones: [] },
  { code: "0206", name: "Sansare", departmentCode: "02", zones: [] },
  { code: "0207", name: "Sanarate", departmentCode: "02", zones: [] },
  { code: "0208", name: "San Antonio La Paz", departmentCode: "02", zones: [] },
  { code: "0301", name: "Antigua Guatemala", departmentCode: "03", zones: [] },
  { code: "0302", name: "Jocotenango", departmentCode: "03", zones: [] },
  { code: "0303", name: "Pastores", departmentCode: "03", zones: [] },
  { code: "0304", name: "Sumpango", departmentCode: "03", zones: [] },
  { code: "0305", name: "Santo Domingo Xenacoj", departmentCode: "03", zones: [] },
  { code: "0306", name: "Santiago Sacatepéquez", departmentCode: "03", zones: [] },
  { code: "0307", name: "San Bartolomé Milpas Altas", departmentCode: "03", zones: [] },
  { code: "0308", name: "San Lucas Sacatepéquez", departmentCode: "03", zones: [] },
  { code: "0309", name: "Santa Lucía Milpas Altas", departmentCode: "03", zones: [] },
  { code: "0310", name: "Magdalena Milpas Altas", departmentCode: "03", zones: [] },
  { code: "0311", name: "Santa María de Jesús", departmentCode: "03", zones: [] },
  { code: "0312", name: "Ciudad Vieja", departmentCode: "03", zones: [] },
  { code: "0313", name: "San Miguel Dueñas", departmentCode: "03", zones: [] },
  { code: "0314", name: "Alotenango", departmentCode: "03", zones: [] },
  { code: "0315", name: "San Antonio Aguas Calientes", departmentCode: "03", zones: [] },
  { code: "0316", name: "Santa Catarina Barahona", departmentCode: "03", zones: [] },
  { code: "0401", name: "Chimaltenango", departmentCode: "04", zones: [] },
  { code: "0402", name: "San José Poaquil", departmentCode: "04", zones: [] },
  { code: "0403", name: "San Martín Jilotepeque", departmentCode: "04", zones: [] },
  { code: "0404", name: "San Juan Comalapa", departmentCode: "04", zones: [] },
  { code: "0405", name: "Santa Apolonia", departmentCode: "04", zones: [] },
  { code: "0406", name: "Tecpán Guatemala", departmentCode: "04", zones: [] },
  { code: "0407", name: "Patzún", departmentCode: "04", zones: [] },
  { code: "0408", name: "San Miguel Pochuta", departmentCode: "04", zones: [] },
  { code: "0409", name: "Patzicía", departmentCode: "04", zones: [] },
  { code: "0410", name: "Santa Cruz Balanyá", departmentCode: "04", zones: [] },
  { code: "0411", name: "Acatenango", departmentCode: "04", zones: [] },
  { code: "0412", name: "San Pedro Yepocapa", departmentCode: "04", zones: [] },
  { code: "0413", name: "San Andrés Itzapa", departmentCode: "04", zones: [] },
  { code: "0414", name: "Parramos", departmentCode: "04", zones: [] },
  { code: "0415", name: "Zaragoza", departmentCode: "04", zones: [] },
  { code: "0416", name: "El Tejar", departmentCode: "04", zones: [] },
  { code: "0501", name: "Escuintla", departmentCode: "05", zones: [] },
  { code: "0502", name: "Santa Lucía Cotzumalguapa", departmentCode: "05", zones: [] },
  { code: "0503", name: "La Democracia", departmentCode: "05", zones: [] },
  { code: "0504", name: "Siquinalá", departmentCode: "05", zones: [] },
  { code: "0505", name: "Masagua", departmentCode: "05", zones: [] },
  { code: "0506", name: "Tiquisate", departmentCode: "05", zones: [] },
  { code: "0507", name: "La Gomera", departmentCode: "05", zones: [] },
  { code: "0508", name: "Guanagazapa", departmentCode: "05", zones: [] },
  { code: "0509", name: "San José", departmentCode: "05", zones: [] },
  { code: "0510", name: "Iztapa", departmentCode: "05", zones: [] },
  { code: "0511", name: "Palín", departmentCode: "05", zones: [] },
  { code: "0512", name: "San Vicente Pacaya", departmentCode: "05", zones: [] },
  { code: "0513", name: "Nueva Concepción", departmentCode: "05", zones: [] },
  { code: "0514", name: "Sipacate", departmentCode: "05", zones: [] },
  { code: "0601", name: "Cuilapa", departmentCode: "06", zones: [] },
  { code: "0602", name: "Barberena", departmentCode: "06", zones: [] },
  { code: "0603", name: "Santa Rosa de Lima", departmentCode: "06", zones: [] },
  { code: "0604", name: "Casillas", departmentCode: "06", zones: [] },
  { code: "0605", name: "San Rafael Las Flores", departmentCode: "06", zones: [] },
  { code: "0606", name: "Oratorio", departmentCode: "06", zones: [] },
  { code: "0607", name: "San Juan Tecuaco", departmentCode: "06", zones: [] },
  { code: "0608", name: "Chiquimulilla", departmentCode: "06", zones: [] },
  { code: "0609", name: "Taxisco", departmentCode: "06", zones: [] },
  { code: "0610", name: "Santa María Ixhuatán", departmentCode: "06", zones: [] },
  { code: "0611", name: "Guazacapán", departmentCode: "06", zones: [] },
  { code: "0612", name: "Santa Cruz Naranjo", departmentCode: "06", zones: [] },
  { code: "0613", name: "Pueblo Nuevo Viñas", departmentCode: "06", zones: [] },
  { code: "0614", name: "Nueva Santa Rosa", departmentCode: "06", zones: [] },
  { code: "0701", name: "Sololá", departmentCode: "07", zones: [] },
  { code: "0702", name: "San José Chacayá", departmentCode: "07", zones: [] },
  { code: "0703", name: "Santa María Visitación", departmentCode: "07", zones: [] },
  { code: "0704", name: "Santa Lucía Utatlán", departmentCode: "07", zones: [] },
  { code: "0705", name: "Nahualá", departmentCode: "07", zones: [] },
  { code: "0706", name: "Santa Catarina Ixtahuacán", departmentCode: "07", zones: [] },
  { code: "0707", name: "Santa Clara La Laguna", departmentCode: "07", zones: [] },
  { code: "0708", name: "Concepción", departmentCode: "07", zones: [] },
  { code: "0709", name: "San Andrés Semetabaj", departmentCode: "07", zones: [] },
  { code: "0710", name: "Panajachel", departmentCode: "07", zones: [] },
  { code: "0711", name: "Santa Catarina Palopó", departmentCode: "07", zones: [] },
  { code: "0712", name: "San Antonio Palopó", departmentCode: "07", zones: [] },
  { code: "0713", name: "San Lucas Tolimán", departmentCode: "07", zones: [] },
  { code: "0714", name: "Santa Cruz La Laguna", departmentCode: "07", zones: [] },
  { code: "0715", name: "San Pablo La Laguna", departmentCode: "07", zones: [] },
  { code: "0716", name: "San Marcos La Laguna", departmentCode: "07", zones: [] },
  { code: "0717", name: "San Juan La Laguna", departmentCode: "07", zones: [] },
  { code: "0718", name: "San Pedro La Laguna", departmentCode: "07", zones: [] },
  { code: "0719", name: "Santiago Atitlán", departmentCode: "07", zones: [] },
  { code: "0801", name: "Totonicapán", departmentCode: "08", zones: [] },
  { code: "0802", name: "San Cristóbal Totonicapán", departmentCode: "08", zones: [] },
  { code: "0803", name: "San Francisco El Alto", departmentCode: "08", zones: [] },
  { code: "0804", name: "San Andrés Xecul", departmentCode: "08", zones: [] },
  { code: "0805", name: "Momostenango", departmentCode: "08", zones: [] },
  { code: "0806", name: "Santa María Chiquimula", departmentCode: "08", zones: [] },
  { code: "0807", name: "Santa Lucía La Reforma", departmentCode: "08", zones: [] },
  { code: "0808", name: "San Bartolo Aguas Calientes", departmentCode: "08", zones: [] },
  {
    code: "0901",
    name: "Quetzaltenango",
    departmentCode: "09",
    zones: [
      "Zona 1",
      "Zona 2",
      "Zona 3",
      "Zona 4",
      "Zona 5",
      "Zona 6",
      "Zona 7",
      "Zona 8",
      "Zona 9",
      "Zona 10",
      "Zona 11",
    ],
  },
  { code: "0902", name: "Salcajá", departmentCode: "09", zones: [] },
  { code: "0903", name: "Olintepeque", departmentCode: "09", zones: [] },
  { code: "0904", name: "San Carlos Sija", departmentCode: "09", zones: [] },
  { code: "0905", name: "Sibilia", departmentCode: "09", zones: [] },
  { code: "0906", name: "Cabricán", departmentCode: "09", zones: [] },
  { code: "0907", name: "Cajolá", departmentCode: "09", zones: [] },
  { code: "0908", name: "San Miguel Sigüilá", departmentCode: "09", zones: [] },
  { code: "0909", name: "San Juan Ostuncalco", departmentCode: "09", zones: [] },
  { code: "0910", name: "San Mateo", departmentCode: "09", zones: [] },
  { code: "0911", name: "Concepción Chiquirichapa", departmentCode: "09", zones: [] },
  { code: "0912", name: "San Martín Sacatepéquez", departmentCode: "09", zones: [] },
  { code: "0913", name: "Almolonga", departmentCode: "09", zones: [] },
  { code: "0914", name: "Cantel", departmentCode: "09", zones: [] },
  { code: "0915", name: "Huitán", departmentCode: "09", zones: [] },
  { code: "0916", name: "Zunil", departmentCode: "09", zones: [] },
  { code: "0917", name: "Colomba Costa Cuca", departmentCode: "09", zones: [] },
  { code: "0918", name: "San Francisco La Unión", departmentCode: "09", zones: [] },
  { code: "0919", name: "El Palmar", departmentCode: "09", zones: [] },
  { code: "0920", name: "Coatepeque", departmentCode: "09", zones: [] },
  { code: "0921", name: "Génova", departmentCode: "09", zones: [] },
  { code: "0922", name: "Flores Costa Cuca", departmentCode: "09", zones: [] },
  { code: "0923", name: "La Esperanza", departmentCode: "09", zones: [] },
  { code: "0924", name: "Palestina de Los Altos", departmentCode: "09", zones: [] },
  { code: "1001", name: "Mazatenango", departmentCode: "10", zones: [] },
  { code: "1002", name: "Cuyotenango", departmentCode: "10", zones: [] },
  { code: "1003", name: "San Francisco Zapotitlán", departmentCode: "10", zones: [] },
  { code: "1004", name: "San Bernardino", departmentCode: "10", zones: [] },
  { code: "1005", name: "San José El Ídolo", departmentCode: "10", zones: [] },
  { code: "1006", name: "Santo Domingo Suchitepéquez", departmentCode: "10", zones: [] },
  { code: "1007", name: "San Lorenzo", departmentCode: "10", zones: [] },
  { code: "1008", name: "Samayac", departmentCode: "10", zones: [] },
  { code: "1009", name: "San Pablo Jocopilas", departmentCode: "10", zones: [] },
  { code: "1010", name: "San Antonio Suchitepéquez", departmentCode: "10", zones: [] },
  { code: "1011", name: "San Miguel Panán", departmentCode: "10", zones: [] },
  { code: "1012", name: "San Gabriel", departmentCode: "10", zones: [] },
  { code: "1013", name: "Chicacao", departmentCode: "10", zones: [] },
  { code: "1014", name: "Patulul", departmentCode: "10", zones: [] },
  { code: "1015", name: "Santa Bárbara", departmentCode: "10", zones: [] },
  { code: "1016", name: "San Juan Bautista", departmentCode: "10", zones: [] },
  { code: "1017", name: "Santo Tomás La Unión", departmentCode: "10", zones: [] },
  { code: "1018", name: "Zunilito", departmentCode: "10", zones: [] },
  { code: "1019", name: "Pueblo Nuevo", departmentCode: "10", zones: [] },
  { code: "1020", name: "Río Bravo", departmentCode: "10", zones: [] },
  { code: "1021", name: "San José La Máquina", departmentCode: "10", zones: [] },
  { code: "1101", name: "Retalhuleu", departmentCode: "11", zones: [] },
  { code: "1102", name: "San Sebastián", departmentCode: "11", zones: [] },
  { code: "1103", name: "Santa Cruz Muluá", departmentCode: "11", zones: [] },
  { code: "1104", name: "San Martín Zapotitlán", departmentCode: "11", zones: [] },
  { code: "1105", name: "San Felipe", departmentCode: "11", zones: [] },
  { code: "1106", name: "San Andrés Villa Seca", departmentCode: "11", zones: [] },
  { code: "1107", name: "Champerico", departmentCode: "11", zones: [] },
  { code: "1108", name: "Nuevo San Carlos", departmentCode: "11", zones: [] },
  { code: "1109", name: "El Asintal", departmentCode: "11", zones: [] },
  { code: "1201", name: "San Marcos", departmentCode: "12", zones: [] },
  { code: "1202", name: "San Pedro Sacatepéquez", departmentCode: "12", zones: [] },
  { code: "1203", name: "San Antonio Sacatepéquez", departmentCode: "12", zones: [] },
  { code: "1204", name: "Comitancillo", departmentCode: "12", zones: [] },
  { code: "1205", name: "San Miguel Ixtahuacán", departmentCode: "12", zones: [] },
  { code: "1206", name: "Concepción Tutuapa", departmentCode: "12", zones: [] },
  { code: "1207", name: "Tacaná", departmentCode: "12", zones: [] },
  { code: "1208", name: "Sibinal", departmentCode: "12", zones: [] },
  { code: "1209", name: "Tajumulco", departmentCode: "12", zones: [] },
  { code: "1210", name: "Tejutla", departmentCode: "12", zones: [] },
  { code: "1211", name: "San Rafael Pie de la Cuesta", departmentCode: "12", zones: [] },
  { code: "1212", name: "Nuevo Progreso", departmentCode: "12", zones: [] },
  { code: "1213", name: "El Tumbador", departmentCode: "12", zones: [] },
  { code: "1214", name: "El Rodeo", departmentCode: "12", zones: [] },
  { code: "1215", name: "Malacatán", departmentCode: "12", zones: [] },
  { code: "1216", name: "Catarina", departmentCode: "12", zones: [] },
  { code: "1217", name: "Ayutla", departmentCode: "12", zones: [] },
  { code: "1218", name: "Ocós", departmentCode: "12", zones: [] },
  { code: "1219", name: "San Pablo", departmentCode: "12", zones: [] },
  { code: "1220", name: "El Quetzal", departmentCode: "12", zones: [] },
  { code: "1221", name: "La Reforma", departmentCode: "12", zones: [] },
  { code: "1222", name: "Pajapita", departmentCode: "12", zones: [] },
  { code: "1223", name: "Ixchiguán", departmentCode: "12", zones: [] },
  { code: "1224", name: "San José Ojetenam", departmentCode: "12", zones: [] },
  { code: "1225", name: "San Cristóbal Cucho", departmentCode: "12", zones: [] },
  { code: "1226", name: "Sipacapa", departmentCode: "12", zones: [] },
  { code: "1227", name: "Esquipulas Palo Gordo", departmentCode: "12", zones: [] },
  { code: "1228", name: "Río Blanco", departmentCode: "12", zones: [] },
  { code: "1229", name: "San Lorenzo", departmentCode: "12", zones: [] },
  { code: "1230", name: "La Blanca", departmentCode: "12", zones: [] },
  { code: "1301", name: "Huehuetenango", departmentCode: "13", zones: [] },
  { code: "1302", name: "Chiantla", departmentCode: "13", zones: [] },
  { code: "1303", name: "Malacatancito", departmentCode: "13", zones: [] },
  { code: "1304", name: "Cuilco", departmentCode: "13", zones: [] },
  { code: "1305", name: "Nentón", departmentCode: "13", zones: [] },
  { code: "1306", name: "San Pedro Necta", departmentCode: "13", zones: [] },
  { code: "1307", name: "Jacaltenango", departmentCode: "13", zones: [] },
  { code: "1308", name: "San Pedro Soloma", departmentCode: "13", zones: [] },
  { code: "1309", name: "San Ildefonso Ixtahuacán", departmentCode: "13", zones: [] },
  { code: "1310", name: "Santa Bárbara", departmentCode: "13", zones: [] },
  { code: "1311", name: "La Libertad", departmentCode: "13", zones: [] },
  { code: "1312", name: "La Democracia", departmentCode: "13", zones: [] },
  { code: "1313", name: "San Miguel Acatán", departmentCode: "13", zones: [] },
  { code: "1314", name: "San Rafael La Independencia", departmentCode: "13", zones: [] },
  { code: "1315", name: "Todos Santos Cuchumatán", departmentCode: "13", zones: [] },
  { code: "1316", name: "San Juan Atitán", departmentCode: "13", zones: [] },
  { code: "1317", name: "Santa Eulalia", departmentCode: "13", zones: [] },
  { code: "1318", name: "San Mateo Ixtatán", departmentCode: "13", zones: [] },
  { code: "1319", name: "Colotenango", departmentCode: "13", zones: [] },
  { code: "1320", name: "San Sebastián Huehuetenango", departmentCode: "13", zones: [] },
  { code: "1321", name: "Tectitán", departmentCode: "13", zones: [] },
  { code: "1322", name: "Concepción Huista", departmentCode: "13", zones: [] },
  { code: "1323", name: "San Juan Ixcoy", departmentCode: "13", zones: [] },
  { code: "1324", name: "San Antonio Huista", departmentCode: "13", zones: [] },
  { code: "1325", name: "San Sebastián Coatán", departmentCode: "13", zones: [] },
  { code: "1326", name: "Santa Cruz Barillas", departmentCode: "13", zones: [] },
  { code: "1327", name: "Aguacatán", departmentCode: "13", zones: [] },
  { code: "1328", name: "San Rafael Petzal", departmentCode: "13", zones: [] },
  { code: "1329", name: "San Gaspar Ixchil", departmentCode: "13", zones: [] },
  { code: "1330", name: "Santiago Chimaltenango", departmentCode: "13", zones: [] },
  { code: "1331", name: "Santa Ana Huista", departmentCode: "13", zones: [] },
  { code: "1332", name: "Unión Cantinil", departmentCode: "13", zones: [] },
  { code: "1333", name: "Petatán", departmentCode: "13", zones: [] },
  { code: "1401", name: "Santa Cruz del Quiché", departmentCode: "14", zones: [] },
  { code: "1402", name: "Chiché", departmentCode: "14", zones: [] },
  { code: "1403", name: "Chinique", departmentCode: "14", zones: [] },
  { code: "1404", name: "Zacualpa", departmentCode: "14", zones: [] },
  { code: "1405", name: "Chajul", departmentCode: "14", zones: [] },
  { code: "1406", name: "Santo Tomás Chichicastenango", departmentCode: "14", zones: [] },
  { code: "1407", name: "Patzité", departmentCode: "14", zones: [] },
  { code: "1408", name: "San Antonio Ilotenango", departmentCode: "14", zones: [] },
  { code: "1409", name: "San Pedro Jocopilas", departmentCode: "14", zones: [] },
  { code: "1410", name: "Cunén", departmentCode: "14", zones: [] },
  { code: "1411", name: "San Juan Cotzal", departmentCode: "14", zones: [] },
  { code: "1412", name: "Joyabaj", departmentCode: "14", zones: [] },
  { code: "1413", name: "Santa María Nebaj", departmentCode: "14", zones: [] },
  { code: "1414", name: "San Andrés Sajcabajá", departmentCode: "14", zones: [] },
  { code: "1415", name: "Uspantán", departmentCode: "14", zones: [] },
  { code: "1416", name: "Sacapulas", departmentCode: "14", zones: [] },
  { code: "1417", name: "San Bartolomé Jocotenango", departmentCode: "14", zones: [] },
  { code: "1418", name: "Canillá", departmentCode: "14", zones: [] },
  { code: "1419", name: "Chicamán", departmentCode: "14", zones: [] },
  { code: "1420", name: "Ixcán", departmentCode: "14", zones: [] },
  { code: "1421", name: "Pachalum", departmentCode: "14", zones: [] },
  { code: "1501", name: "Salamá", departmentCode: "15", zones: [] },
  { code: "1502", name: "San Miguel Chicaj", departmentCode: "15", zones: [] },
  { code: "1503", name: "Rabinal", departmentCode: "15", zones: [] },
  { code: "1504", name: "Cubulco", departmentCode: "15", zones: [] },
  { code: "1505", name: "Granados", departmentCode: "15", zones: [] },
  { code: "1506", name: "El Chol", departmentCode: "15", zones: [] },
  { code: "1507", name: "San Jerónimo", departmentCode: "15", zones: [] },
  { code: "1508", name: "Purulhá", departmentCode: "15", zones: [] },
  { code: "1601", name: "Cobán", departmentCode: "16", zones: [] },
  { code: "1602", name: "Santa Cruz Verapaz", departmentCode: "16", zones: [] },
  { code: "1603", name: "San Cristóbal Verapaz", departmentCode: "16", zones: [] },
  { code: "1604", name: "Tactic", departmentCode: "16", zones: [] },
  { code: "1605", name: "Tamahú", departmentCode: "16", zones: [] },
  { code: "1606", name: "Tucurú", departmentCode: "16", zones: [] },
  { code: "1607", name: "Panzós", departmentCode: "16", zones: [] },
  { code: "1608", name: "Senahú", departmentCode: "16", zones: [] },
  { code: "1609", name: "San Pedro Carchá", departmentCode: "16", zones: [] },
  { code: "1610", name: "San Juan Chamelco", departmentCode: "16", zones: [] },
  { code: "1611", name: "Lanquín", departmentCode: "16", zones: [] },
  { code: "1612", name: "Santa María Cahabón", departmentCode: "16", zones: [] },
  { code: "1613", name: "Chisec", departmentCode: "16", zones: [] },
  { code: "1614", name: "Chahal", departmentCode: "16", zones: [] },
  { code: "1615", name: "Fray Bartolomé de las Casas", departmentCode: "16", zones: [] },
  { code: "1616", name: "Santa Catalina La Tinta", departmentCode: "16", zones: [] },
  { code: "1617", name: "Raxruhá", departmentCode: "16", zones: [] },
  { code: "1701", name: "Flores", departmentCode: "17", zones: [] },
  { code: "1702", name: "San José", departmentCode: "17", zones: [] },
  { code: "1703", name: "San Benito", departmentCode: "17", zones: [] },
  { code: "1704", name: "San Andrés", departmentCode: "17", zones: [] },
  { code: "1705", name: "La Libertad", departmentCode: "17", zones: [] },
  { code: "1706", name: "San Francisco", departmentCode: "17", zones: [] },
  { code: "1707", name: "Santa Ana", departmentCode: "17", zones: [] },
  { code: "1708", name: "Dolores", departmentCode: "17", zones: [] },
  { code: "1709", name: "San Luis", departmentCode: "17", zones: [] },
  { code: "1710", name: "Sayaxché", departmentCode: "17", zones: [] },
  { code: "1711", name: "Melchor de Mencos", departmentCode: "17", zones: [] },
  { code: "1712", name: "Poptún", departmentCode: "17", zones: [] },
  { code: "1713", name: "Las Cruces", departmentCode: "17", zones: [] },
  { code: "1714", name: "El Chal", departmentCode: "17", zones: [] },
  { code: "1801", name: "Puerto Barrios", departmentCode: "18", zones: [] },
  { code: "1802", name: "Livingston", departmentCode: "18", zones: [] },
  { code: "1803", name: "El Estor", departmentCode: "18", zones: [] },
  { code: "1804", name: "Morales", departmentCode: "18", zones: [] },
  { code: "1805", name: "Los Amates", departmentCode: "18", zones: [] },
  { code: "1901", name: "Zacapa", departmentCode: "19", zones: [] },
  { code: "1902", name: "Estanzuela", departmentCode: "19", zones: [] },
  { code: "1903", name: "Río Hondo", departmentCode: "19", zones: [] },
  { code: "1904", name: "Gualán", departmentCode: "19", zones: [] },
  { code: "1905", name: "Teculután", departmentCode: "19", zones: [] },
  { code: "1906", name: "Usumatlán", departmentCode: "19", zones: [] },
  { code: "1907", name: "Cabañas", departmentCode: "19", zones: [] },
  { code: "1908", name: "San Diego", departmentCode: "19", zones: [] },
  { code: "1909", name: "La Unión", departmentCode: "19", zones: [] },
  { code: "1910", name: "Huité", departmentCode: "19", zones: [] },
  { code: "1911", name: "San Jorge", departmentCode: "19", zones: [] },
  { code: "2001", name: "Chiquimula", departmentCode: "20", zones: [] },
  { code: "2002", name: "San José La Arada", departmentCode: "20", zones: [] },
  { code: "2003", name: "San Juan Ermita", departmentCode: "20", zones: [] },
  { code: "2004", name: "Jocotán", departmentCode: "20", zones: [] },
  { code: "2005", name: "Camotán", departmentCode: "20", zones: [] },
  { code: "2006", name: "Olopa", departmentCode: "20", zones: [] },
  { code: "2007", name: "Esquipulas", departmentCode: "20", zones: [] },
  { code: "2008", name: "Concepción Las Minas", departmentCode: "20", zones: [] },
  { code: "2009", name: "Quezaltepeque", departmentCode: "20", zones: [] },
  { code: "2010", name: "San Jacinto", departmentCode: "20", zones: [] },
  { code: "2011", name: "Ipala", departmentCode: "20", zones: [] },
  { code: "2101", name: "Jalapa", departmentCode: "21", zones: [] },
  { code: "2102", name: "San Pedro Pinula", departmentCode: "21", zones: [] },
  { code: "2103", name: "San Luis Jilotepeque", departmentCode: "21", zones: [] },
  { code: "2104", name: "San Manuel Chaparrón", departmentCode: "21", zones: [] },
  { code: "2105", name: "San Carlos Alzatate", departmentCode: "21", zones: [] },
  { code: "2106", name: "Monjas", departmentCode: "21", zones: [] },
  { code: "2107", name: "Mataquescuintla", departmentCode: "21", zones: [] },
  { code: "2201", name: "Jutiapa", departmentCode: "22", zones: [] },
  { code: "2202", name: "El Progreso", departmentCode: "22", zones: [] },
  { code: "2203", name: "Santa Catarina Mita", departmentCode: "22", zones: [] },
  { code: "2204", name: "Agua Blanca", departmentCode: "22", zones: [] },
  { code: "2205", name: "Asunción Mita", departmentCode: "22", zones: [] },
  { code: "2206", name: "Yupiltepeque", departmentCode: "22", zones: [] },
  { code: "2207", name: "Atescatempa", departmentCode: "22", zones: [] },
  { code: "2208", name: "Jerez", departmentCode: "22", zones: [] },
  { code: "2209", name: "El Adelanto", departmentCode: "22", zones: [] },
  { code: "2210", name: "Zapotitlán", departmentCode: "22", zones: [] },
  { code: "2211", name: "Comapa", departmentCode: "22", zones: [] },
  { code: "2212", name: "Jalpatagua", departmentCode: "22", zones: [] },
  { code: "2213", name: "Conguaco", departmentCode: "22", zones: [] },
  { code: "2214", name: "Moyuta", departmentCode: "22", zones: [] },
  { code: "2215", name: "Pasaco", departmentCode: "22", zones: [] },
  { code: "2216", name: "San José Acatempa", departmentCode: "22", zones: [] },
  { code: "2217", name: "Quesada", departmentCode: "22", zones: [] },
];
